meka_roscontrol:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Mode controllers used to switch between control methods ----------------------------
  position_joint_mode_controller:
    type: joint_mode_controller/JointModeController
    joint_mode: 1 # position

  velocity_joint_mode_controller:
    type: joint_mode_controller/JointModeController
    joint_mode: 2 # velocity

  # Position only controllers ----------------------------------------------

  zlift_position_controller:
    type: "position_controllers/JointGroupPositionController"
    joints: 
      - zlift_j0

  zlift_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - zlift_j0
    
    constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 0.05
      zlift_j0:
        goal: 0.1

      state_publish_rate: 50
      action_monitor_rate: 20
      #hold_trajectory_duration: 0 #defaults to 0.5

  torso_position_controller:
    type: "position_controllers/JointGroupPositionController"
    joints:
      - torso_j0
      - torso_j1
      
  torso_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - torso_j0
      - torso_j1

    constraints:
      goal_time: 0.5                   # Defaults to zero
      stopped_velocity_tolerance: 0.05 # Defaults to 0.01
      torso_j0:
        goal: 0.1       
      torso_j1:
        goal: 0.1       
      
    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

  head_position_controller:
    type: "position_controllers/JointGroupPositionController"
    joints:
      - head_j0
      - head_j1
      
  head_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - head_j0
      - head_j1

    constraints:
      goal_time: 0.5                   # Defaults to zero
      stopped_velocity_tolerance: 0.05 # Defaults to 0.01
      head_j0:
        goal: 0.1       
      head_j1:
        goal: 0.1       
      
    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

  #right_arm_stiffness_controller:
  #  type: "position_controllers/JointGroupPositionController"
  #  joints:
  #    - right_arm_j0_stiffness
  #    - right_arm_j1_stiffness
  #    - right_arm_j2_stiffness
  #    - right_arm_j3_stiffness
  #    - right_arm_j4_stiffness
  #    - right_arm_j5_stiffness
  #    - right_arm_j6_stiffness
  #    
  stiffness_controller:
    type: "position_controllers/JointGroupPositionController"
    joints:
      - right_arm_j0_stiffness
      - right_arm_j1_stiffness
      - right_arm_j2_stiffness
      - right_arm_j3_stiffness
      - right_arm_j4_stiffness
      - right_arm_j5_stiffness
      - right_arm_j6_stiffness
      - left_arm_j0_stiffness
      - left_arm_j1_stiffness
      - left_arm_j2_stiffness
      - left_arm_j3_stiffness
      - left_arm_j4_stiffness
      - left_arm_j5_stiffness
      - left_arm_j6_stiffness
      - right_hand_j0_stiffness
      - right_hand_j1_stiffness
      - right_hand_j2_stiffness
      - right_hand_j3_stiffness
      - right_hand_j4_stiffness
      - left_hand_j0_stiffness
      - left_hand_j1_stiffness
      - left_hand_j2_stiffness
      - left_hand_j3_stiffness
      - left_hand_j4_stiffness
      - torso_j0_stiffness
      - torso_j1_stiffness
      - zlift_j0_stiffness

  right_arm_position_controller:
    type: "position_controllers/JointGroupPositionController"
    joints:
      - right_arm_j0
      - right_arm_j1
      - right_arm_j2
      - right_arm_j3
      - right_arm_j4
      - right_arm_j5
      - right_arm_j6

  left_arm_position_controller:
    type: "position_controllers/JointGroupPositionController"
    joints:
      - left_arm_j0
      - left_arm_j1
      - left_arm_j2
      - left_arm_j3
      - left_arm_j4
      - left_arm_j5
      - left_arm_j6

  left_arm_stiffness_controller:
    type: "position_controllers/JointGroupPositionController"
    joints:
      - left_arm_j0_stiffness
      - left_arm_j1_stiffness
      - left_arm_j2_stiffness
      - left_arm_j3_stiffness
      - left_arm_j4_stiffness
      - left_arm_j5_stiffness
      - left_arm_j6_stiffness

  right_hand_position_controller:
    type: "position_controllers/JointGroupPositionController"
    joints:
      - right_hand_j0
      - right_hand_j1
      - right_hand_j2
      - right_hand_j3
      - right_hand_j4
      
  right_hand_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - right_hand_j0
      - right_hand_j1
      - right_hand_j2
      - right_hand_j3
      - right_hand_j4

    constraints:
      goal_time: 0.5                   # Defaults to zero
      stopped_velocity_tolerance: 0.05 # Defaults to 0.01
      right_hand_j0:
        goal: 0.6
      right_hand_j1:
        goal: 0.3
      right_hand_j2:
        goal: 0.4
      right_hand_j3:
        goal: 0.4
      right_hand_j4:
        goal: 0.75

    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

  left_hand_position_controller:
    type: "position_controllers/JointGroupPositionController"
    joints:
      - left_hand_j0
      - left_hand_j1
      - left_hand_j2
      - left_hand_j3
      - left_hand_j4

  left_hand_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - left_hand_j0
      - left_hand_j1
      - left_hand_j2
      - left_hand_j3
      - left_hand_j4

    constraints:
      goal_time: 1.0                   # Defaults to zero
      stopped_velocity_tolerance: 0.05 # Defaults to 0.01
      left_hand_j0:
        goal: 0.6
      left_hand_j1:
        goal: 0.2
      left_hand_j2:
        goal: 0.4
      left_hand_j3:
        goal: 0.4
      left_hand_j4:
        goal: 0.75

    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

  # Position - Right and Left Joint Position Trajectory Controllers -------------------
  left_arm_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - left_arm_j0
      - left_arm_j1
      - left_arm_j2
      - left_arm_j3
      - left_arm_j4
      - left_arm_j5
      - left_arm_j6

    constraints:
      goal_time: 0.5                   # Defaults to zero
      stopped_velocity_tolerance: 0.05 # Defaults to 0.01
      left_arm_j0:
        goal: 0       
      left_arm_j1:
        goal: 0       
      left_arm_j2:
        goal: 0       
      left_arm_j3:
        goal: 0       
      left_arm_j4:
        goal: 0       
      left_arm_j5:
        goal: 0       
      left_arm_j6:
        goal: 0      

    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

  right_arm_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - right_arm_j0
      - right_arm_j1
      - right_arm_j2
      - right_arm_j3
      - right_arm_j4
      - right_arm_j5
      - right_arm_j6

    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.05
      right_arm_j0:
        goal: 0  
      right_arm_j1:
        goal: 0 
      right_arm_j2:
        goal: 0
      right_arm_j3:
        goal: 0
      right_arm_j4:
        goal: 0
      right_arm_j5:
        goal: 0
      right_arm_j6:
        goal: 0

    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5
    stop_trajectory_duration: 0.1        # smoother stop

  # Velocity - Right and Left Joint Velocity Trajectory Controllers -------------------
  left_arm_velocity_trajectory_controller:
    type: "velocity_controllers/JointTrajectoryController"
    joints:
      - left_arm_j0
      - left_arm_j1
      - left_arm_j2
      - left_arm_j3
      - left_arm_j4
      - left_arm_j5
      - left_arm_j6

    constraints:
      goal_time: 2.0                   # Defaults to zero
      stopped_velocity_tolerance: 0.4 # Defaults to 0.01
      left_arm_j0:
        trajectory: 0 
        goal: 0.2       
      left_arm_j1:
        trajectory: 0 
        goal: 0.2       
      left_arm_j2:
        trajectory: 0 
        goal: 0.2       
      left_arm_j3:
        trajectory: 0 
        goal: 0.2       
      left_arm_j4:
        trajectory: 0 
        goal: 0.2       
      left_arm_j5:
        trajectory: 0 
        goal: 0.2       
      left_arm_j6:
        trajectory: 0 
        goal: 0.2       

    gains:
      left_arm_j0: {p: 2.0,  i: 0.01, d: 1.0, i_clamp: 1}
      left_arm_j1: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      left_arm_j2: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      left_arm_j3: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      left_arm_j4: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      left_arm_j5: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      left_arm_j6: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}

    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5
    stop_trajectory_duration: 0.1        # smoother stop

  right_arm_velocity_trajectory_controller:
    type: "velocity_controllers/JointTrajectoryController"
    joints:
      - right_arm_j0
      - right_arm_j1
      - right_arm_j2
      - right_arm_j3
      - right_arm_j4
      - right_arm_j5
      - right_arm_j6

    constraints:
      goal_time: 3.0                   
      stopped_velocity_tolerance: 0.04
      right_arm_j0:
        trajectory: 0 
        goal: 0.2       
      right_arm_j1:
        trajectory: 0 
        goal: 0.2       
      right_arm_j2:
        trajectory: 0 
        goal: 0.2       
      right_arm_j3:
        trajectory: 0 
        goal: 0.2       
      right_arm_j4:
        trajectory: 0 
        goal: 0.2       
      right_arm_j5:
        trajectory: 0 
        goal: 0.2       
      right_arm_j6:
        trajectory: 0 
        goal: 0.2       

    gains:
      right_arm_j0: {p: 2.0,  i: 0.01, d: 1.0, i_clamp: 1}
      right_arm_j1: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      right_arm_j2: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      right_arm_j3: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      right_arm_j4: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      right_arm_j5: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      right_arm_j6: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}

    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5
